package com.example.demo.exception.model;


public enum ErrorCode {
    USER_NOT_FOUND,
    CATEGORY_NOT_FOUND,
    COURSE_NOT_FOUND,
    INSTRUCTOR_NOT_FOUND,
    MODULE_NOT_FOUND,
    USER_ALREADY_EXISTS,
    CATEGORY_ALREADY_EXISTS,
    COURSE_ALREADY_EXISTS,
    MODULE_ALREADY_EXISTS,
    TITLE_ALREADY_EXISTS,
    SLUG_NOT_FOUND,
    SLUG_ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,
    VALIDATION_FAILED,
    ACCESS_DENIED,
    UNAUTHORIZED,
    CATEGORY_ALREADY_ARCHIVED,
    COURSE_ALREADY_ARCHIVED,
    INSTRUCTOR_ALREADY_ARCHIVED,
    MODULE_ALREADY_ARCHIVED,
    ENROLLMENT_NOT_FOUND,
    ENROLLMENT_ALREADY_EXISTS,
    CATEGORY_HAS_ACTIVE_COURSES,
    COURSE_HAS_ACTIVE_MODULES,
    CANNOT_DEACTIVATE_CATEGORY_THROUGH_UPDATE_METHOD_PLEASE_USE_ARCHIVE_METHOD_INSTEAD,
    CANNOT_DEACTIVATE_COURSE_THROUGH_UPDATE_METHOD_PLEASE_USE_ARCHIVE_METHOD_INSTEAD,
    CANNOT_DEACTIVATE_INSTRUCTOR_THROUGH_UPDATE_METHOD_PLEASE_USE_ARCHIVE_METHOD_INSTEAD,
    CANNOT_DEACTIVATE_MODULE_THROUGH_UPDATE_METHOD_PLEASE_USE_ARCHIVE_METHOD_INSTEAD,
    USER_IS_NOT_AN_INSTRUCTOR,
    USER_IS_NOT_A_STUDENT,
    USER_ALREADY_ENROLLED_IN_COURSE,
    INVALID_INPUT,
    INACTIVE_USER,
    INACTIVE_COURSE,
    ;



}

